sudo: required
language: c
services:
- docker
compiler:
- gcc
- clang
env:
  matrix:
  - coverity_scan_run_condition='"$CC" = gcc'
  global:
  # COVERITY_SCAN_TOKEN
  - secure: gTif84rZ6XT6ouay6FxO8GY2RSpjVIXOf38G2OH1RFhzrvLa3r4tnE6QRSv7/af2BgM+rhXHUZA5eua6LiS4zIK/UGoBNmeCpdsQYIBqUptYt4sIlYbl1Hwimcd5FqUD19/mokP2snAmnB+s2Z9zC4Y668dV28OAdPf6pOKjW1ivseosy7WKisHnm+NwRvJ5gbEBspwFxd05vDs6dcsx8TRakhQxhJ+XWPoljLH9GHEaRdEuLCWcEAf8q0CfOP15I+PmQqxQ6NGKJJy2dFuIObT8ojOFt7ybngJhY3cPSa/tpmSQDZFaLVHtoYAuUKLk0F5mut9Oog6W3IBEGMAjKYGy2r/WcsKEl2lsQpbtWIRA9qyJT63kpft1yPpuz1AyqebQHW+rbZfnGlclP860ip5d2pTk9l+VLLvXRptawInyH5c3y74h7BgrWJao4xq5iHi49/SegOVT7bT5bsfuUwTMronD0HSZeZJMwPVLg+F3ipk8e/9CMLr6zC9R9X/vuKJF2mya5SOVonLqExE+a0wIGFR2uWWdxHAVZLen8MEJade2ssnaamHis/ADJFjTqg6aKhqAsQGlzRT0F+4wQFht5quP3vWB4B8S1dNP6240a1A9YCG6T2HM3sCNbF8RNqWzcWSesYTl8mg/VU8GYF3BglCxGAxrMW9OFpuHCkQ=
script:
  - ./.ci/travis.run

after_failure:
  - find . -name test-suite.log | xargs cat
